version: 2

references:
  workspace: &workspace
    ~/repo
  container_config: &container_config
    docker:
      - image: circleci/node:7.10
    working_directory: *workspace
  node_modules-cache-key: &node_modules-cache-key
    dependency-cache-{{ checksum "package.json" }}

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: *node_modules-cache-key
      - run: yarn install
      - save_cache:
          key: *node_modules-cache-key
          paths:
            - node_modules
      - persist_to_workspace:
          root: *workspace
          paths:
            - ./*

  storybook:
    <<: *container_config
    steps:
      - attach_workspace:
          at: *workspace
      - run: yarn build-storybook
      - store_artifacts:
          path: storybook-static
          destination: storybook
      - run:
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              PULL_REQUEST_ID="${CIRCLE_PULL_REQUEST##*/pull/}"
              STORYBOOK_URL="$CIRCLE_BUILD_URL/artifacts/$CIRCLE_NODE_INDEX/$CIRCLE_ARTIFACTS/storybook/index.html"
              curl -X POST \
                   -H "Authorization: bearer $GITHUB_API_TOKEN" \
                   -H "Accept: application/vnd.github.v3.html+json" \
                   -d "{\"body\":\"[Storybook] Created ([view stories]($STORYBOOK_URL))\"}" \
                   "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/issues/$PULL_REQUEST_ID/comments"
            else
              echo "[Storybook] Skip post comment"
            fi

workflows:
  version: 2
  setup-and-storybook:
    jobs:
      - setup
      - storybook:
          requires:
            - setup
